Bug 1415619: Add seperate routes for comm-central derived branches.
taskcluster/taskcluster-admin pull request #8
Opened 2017-11-08 22:06 UTC by tomprince

https://bugzilla.mozilla.org/show_bug.cgi?id=1415619

2017-11-16 21:24 UTC, djmitche approved these changes
What does the `-n --all` output for this show?

2017-11-16 21:24 UTC, djmitche commented on src/make-gecko-branch-role.js
> +      'secrets:get:project/releng/<trust-domain>/build/level-3/*'
`<level>`?

2017-11-16 21:28 UTC, djmitche requested changes
oops

2017-11-16 22:04 UTC, tomprince commented
Changes: https://gist.github.com/tomprince/fb0861596430c66e5b24f9962a80aaf5

2017-11-16 22:08 UTC, tomprince commented
Once this is run, the following scopes should be removed from moz-tree:level:3:
- `index:insert-task:docker.images.v2.level-3.*`                                                                                                                                                                   
- `index:insert-task:gecko.cache.level-3.*`
- `queue:route:index.docker.images.v2.level-3.*`                                                                                                                                                                   
- `queue:route:index.gecko.cache.level-3.*`                                                                                                                                                                        
-  `secrets:get:project/releng/gecko/build/level-3/*`
as they are granted to the individual branches now.

2017-11-16 22:08 UTC, tomprince commented
Also, `secrets:get:project/taskcluster/gecko/build/level-3/*` appear to not refer to any secrets.

2017-11-17 15:57 UTC, djmitche approved these changes

2017-11-17 16:00 UTC, djmitche approved these changes
Here's the diff:
```
scope changes required for role repo:hg.mozilla.org/incubator/stylo:*:
- queue:route:index.docker.images.v1.stylo.*
- index:insert-task:docker.images.v1.stylo.*
+ index:route:index:gecko.cache.level-2.*
+ index:insert-task:gecko.cache.level-2.*
+ secrets:get:project/releng/gecko/build/level-2/*
+ queue:route:index.docker.images.v2.level-2.*
scope changes required for role repo:hg.mozilla.org/integration/autoland:*:
- queue:route:index.docker.images.v1.autoland.*
- index:insert-task:docker.images.v1.autoland.*
+ index:route:index:gecko.cache.level-3.*
+ index:insert-task:gecko.cache.level-3.*
+ secrets:get:project/releng/gecko/build/level-3/*
+ queue:route:index.docker.images.v2.level-3.*
no changes required for role repo:hg.mozilla.org/integration/autoland:cron:nightly-*
scope changes required for role repo:hg.mozilla.org/projects/jamun:*:
- queue:route:index.docker.images.v1.jamun.*
- index:insert-task:docker.images.v1.jamun.*
+ index:route:index:gecko.cache.level-3.*
+ index:insert-task:gecko.cache.level-3.*
+ secrets:get:project/releng/gecko/build/level-3/*
+ queue:route:index.docker.images.v2.level-3.*
no changes required for role repo:hg.mozilla.org/projects/jamun:cron:nightly-*
scope changes required for role repo:hg.mozilla.org/projects/gum:*:
+ index:route:index:gecko.cache.level-2.*
+ index:insert-task:gecko.cache.level-2.*
+ secrets:get:project/releng/gecko/build/level-2/*
+ queue:route:index.docker.images.v2.level-2.*
no changes required for role repo:hg.mozilla.org/projects/gum:cron:nightly-*
scope changes required for role repo:hg.mozilla.org/projects/fig:*:
+ index:route:index:gecko.cache.level-2.*
+ index:insert-task:gecko.cache.level-2.*
+ secrets:get:project/releng/gecko/build/level-2/*
+ queue:route:index.docker.images.v2.level-2.*
no changes required for role repo:hg.mozilla.org/projects/fig:cron:nightly-*
scope changes required for role repo:hg.mozilla.org/projects/maple:*:
- queue:route:index.docker.images.v1.maple.*
- index:insert-task:docker.images.v1.maple.*
+ index:route:index:gecko.cache.level-3.*
+ index:insert-task:gecko.cache.level-3.*
+ secrets:get:project/releng/gecko/build/level-3/*
+ queue:route:index.docker.images.v2.level-3.*
no changes required for role repo:hg.mozilla.org/projects/maple:cron:nightly-*
scope changes required for role repo:hg.mozilla.org/projects/larch:*:
+ index:route:index:gecko.cache.level-2.*
+ index:insert-task:gecko.cache.level-2.*
+ secrets:get:project/releng/gecko/build/level-2/*
+ queue:route:index.docker.images.v2.level-2.*
no changes required for role repo:hg.mozilla.org/projects/larch:cron:nightly-*
scope changes required for role repo:hg.mozilla.org/try-comm-central:*:
- queue:route:index.buildbot.branches.try-comm-central.*
- index:insert-task:buildbot.branches.try-comm-central.*
- queue:route:index.buildbot.revisions.*
- index:insert-task:buildbot.revisions.*
- queue:route:index.docker.images.v1.try-comm-central.*
- index:insert-task:docker.images.v1.try-comm-central.*
- queue:route:index.gecko.v2.try-comm-central.*
- index:insert-task:gecko.v2.try-comm-central.*
- project:releng:buildbot-bridge:builder-name:release-try-comm-central-*
- project:releng:buildbot-bridge:builder-name:release-try-comm-central_*
+ queue:route:index.comm.v2.try-comm-central.*
+ index:insert-task:comm.v2.try-comm-central.*
+ index:route:index:comm.cache.level-1.*
+ index:insert-task:comm.cache.level-1.*
+ secrets:get:project/releng/comm/build/level-1/*
scope changes required for role repo:hg.mozilla.org/incubator/stylo-try:*:
+ index:route:index:gecko.cache.level-1.*
+ index:insert-task:gecko.cache.level-1.*
+ secrets:get:project/releng/gecko/build/level-1/*
+ queue:route:index.docker.images.v2.level-1.*
scope changes required for role repo:hg.mozilla.org/try:*:
+ index:route:index:gecko.cache.level-1.*
+ index:insert-task:gecko.cache.level-1.*
+ secrets:get:project/releng/gecko/build/level-1/*
+ queue:route:index.docker.images.v2.level-1.*
scope changes required for role repo:hg.mozilla.org/projects/graphics:*:
+ index:route:index:gecko.cache.level-2.*
+ index:insert-task:gecko.cache.level-2.*
+ secrets:get:project/releng/gecko/build/level-2/*
+ queue:route:index.docker.images.v2.level-2.*
no changes required for role repo:hg.mozilla.org/projects/graphics:cron:nightly-*
scope changes required for role repo:hg.mozilla.org/projects/elm:*:
+ index:route:index:gecko.cache.level-2.*
+ index:insert-task:gecko.cache.level-2.*
+ secrets:get:project/releng/gecko/build/level-2/*
+ queue:route:index.docker.images.v2.level-2.*
no changes required for role repo:hg.mozilla.org/projects/elm:cron:nightly-*
scope changes required for role repo:hg.mozilla.org/projects/ux:*:
+ index:route:index:gecko.cache.level-3.*
+ index:insert-task:gecko.cache.level-3.*
+ secrets:get:project/releng/gecko/build/level-3/*
+ queue:route:index.docker.images.v2.level-3.*
scope changes required for role repo:hg.mozilla.org/projects/cypress:*:
- queue:route:index.buildbot.branches.cypress.*
- index:insert-task:buildbot.branches.cypress.*
- queue:route:index.buildbot.revisions.*
- index:insert-task:buildbot.revisions.*
- queue:route:index.docker.images.v1.cypress.*
- index:insert-task:docker.images.v1.cypress.*
- queue:route:index.gecko.v2.cypress.*
- index:insert-task:gecko.v2.cypress.*
- project:releng:buildbot-bridge:builder-name:release-cypress-*
- project:releng:buildbot-bridge:builder-name:release-cypress_*
+ queue:route:index.comm.v2.cypress.*
+ index:insert-task:comm.v2.cypress.*
+ index:route:index:comm.cache.level-2.*
+ index:insert-task:comm.cache.level-2.*
+ secrets:get:project/releng/comm/build/level-2/*
no changes required for role repo:hg.mozilla.org/projects/cypress:cron:nightly-*
scope changes required for role repo:hg.mozilla.org/projects/birch:*:
+ index:route:index:gecko.cache.level-2.*
+ index:insert-task:gecko.cache.level-2.*
+ secrets:get:project/releng/gecko/build/level-2/*
+ queue:route:index.docker.images.v2.level-2.*
no changes required for role repo:hg.mozilla.org/projects/birch:cron:nightly-*
scope changes required for role repo:hg.mozilla.org/projects/holly:*:
+ index:route:index:gecko.cache.level-2.*
+ index:insert-task:gecko.cache.level-2.*
+ secrets:get:project/releng/gecko/build/level-2/*
+ queue:route:index.docker.images.v2.level-2.*
no changes required for role repo:hg.mozilla.org/projects/holly:cron:nightly-*
scope changes required for role repo:hg.mozilla.org/projects/cedar:*:
+ index:route:index:gecko.cache.level-2.*
+ index:insert-task:gecko.cache.level-2.*
+ secrets:get:project/releng/gecko/build/level-2/*
+ queue:route:index.docker.images.v2.level-2.*
no changes required for role repo:hg.mozilla.org/projects/cedar:cron:nightly-*
scope changes required for role repo:hg.mozilla.org/projects/alder:*:
+ index:route:index:gecko.cache.level-2.*
+ index:insert-task:gecko.cache.level-2.*
+ secrets:get:project/releng/gecko/build/level-2/*
+ queue:route:index.docker.images.v2.level-2.*
no changes required for role repo:hg.mozilla.org/projects/alder:cron:nightly-*
scope changes required for role repo:hg.mozilla.org/comm-central:*:
- queue:route:index.buildbot.branches.comm-central.*
- index:insert-task:buildbot.branches.comm-central.*
- queue:route:index.buildbot.revisions.*
- index:insert-task:buildbot.revisions.*
- queue:route:index.docker.images.v1.comm-central.*
- index:insert-task:docker.images.v1.comm-central.*
- queue:route:index.gecko.v2.comm-central.*
- index:insert-task:gecko.v2.comm-central.*
- project:releng:buildbot-bridge:builder-name:release-comm-central-*
- project:releng:buildbot-bridge:builder-name:release-comm-central_*
+ queue:route:index.comm.v2.comm-central.*
+ index:insert-task:comm.v2.comm-central.*
+ index:route:index:comm.cache.level-3.*
+ index:insert-task:comm.cache.level-3.*
+ secrets:get:project/releng/comm/build/level-3/*
scope changes required for role repo:hg.mozilla.org/mozilla-central:*:
- queue:route:index.docker.images.v1.mozilla-central.*
- index:insert-tas [...]

2017-11-17 16:45 UTC, tomprince commented
The releng secrets are used, the taskcluster ones aren't. I didn't move the taskcluster one because it appears unused currently.

2017-11-17 17:16 UTC, djmitche commented
Ah, OK.

2017-11-17 22:25 UTC, merged